### ISSUE TITLE
Expect 201 not 202 from WHIP server

### ISSUE THREAD

**Issue by lminiero** [x186k/whip-whap-js#1]
Hi,

thanks for sharing a new WHIP client implementation! As part of the [IETF 112 Hackathon](https://www.ietf.org/how/runningcode/hackathons/112-hackathon/), I'm tinkering with other WHIP implementations I've become aware of, so I wanted to test yours too. 

I tried your example by putting the snippet in a web page and setting the url to a [Simple WHIP Server](https://github.com/lminiero/simple-whip-server) endpoint:

```
let url = 'http://localhost:7080/whip/endpoint/test'
let whipwhap = await import('https://cdn.jsdelivr.net/npm/whip-whap-js')
document.write('<video id="video1" autoplay controls muted width="1024" allowfullscreen/>')
let pc = new RTCPeerConnection({ iceServers: [{ urls: 'stun:stun.l.google.com:19302' }] })
pc.addEventListener('iceconnectionstatechange', whipwhap.handleIceStateChange)
pc.addEventListener('negotiationneeded', ev => whipwhap.handleNegotiationNeeded(ev, url))
let gum = await navigator.mediaDevices.getUserMedia({ audio: true, video: true })
pc.addTransceiver(gum.getVideoTracks()[0], { 'direction': 'sendonly' })
pc.addTransceiver(gum.getAudioTracks()[0], { 'direction': 'sendonly' })
let video1 = document.getElementById('video1')
video1.srcObject = gum
video1.play()
```

but that ends in an ICE failure in Janus. Checking the webrtc-internals, I see the code above never calls setRemoteDescription (which I thought was done automatically by `whipwhap.handleNegotiationNeeded(ev, url)` but doesn't seem to be the case), which means STUN always fails since the browser is not aware of the server ICE credentials.

Not sure if I'm doing something wrong or the example snippet needs fixing? Thanks!

**Comment by lminiero** [comment]
Checking the code, this seems to be the problem:

https://github.com/x186k/whip-whap-js/blob/3a7f031c2c5a631b4dbf8a6ddaf162bb9bf6b252/whip-whap-js.js#L98

The stack is expecting a `202` success response, but per the draft you'll get the SDP answer in a `201` (which is what my WHIP server sends back).

**Comment by lminiero** [comment]
I can confirm that changing `202` to `201` there gets it to work :+1:

**Comment by cameronelliott** [comment]
Thrilled to get your feedback, @lminiero 
Thank you.
