### ISSUE TITLE
restartICE problem

### ISSUE THREAD

**Issue by seven1240** [x186k/whip-whap-js#4]
The js is nice and easy to use.

I hit a problem when my server has problem setup ICE, restartICE triggers `negotiationneeded` and in that callback it POST to /api/whap which create a Location: `/api/whap/new-uuid`, so when restartICE being called repeatedly it caused a lot of new-uuid generated on the server.

Question:

- should `negotiationneeded` returns the response.headers.get('Location') so it's possible to DELETE it later?
- should we pass a `state` and Location URL into `negotiationneeded` so when the second time it's being triggered it calls PATCH to the Location URL to update SDP instead of calling POST which means create a new one?

Thanks.

**Comment by cameronelliott** [comment]
Hi Seven, thank you so much for trying whip-whap-js, and thank you for submitting an issue.

I am interested in your PRs, but I might make changes if I believe it improves the software.

For your questions:

https://datatracker.ietf.org/doc/html/draft-ietf-wish-whip-02#section-4



> The js is nice and easy to use. 
Thank you! 😄 
> 
> I hit a problem when my server has problem setup ICE, restartICE triggers `negotiationneeded` and in that callback it POST to /api/whap which create a Location: `/api/whap/new-uuid`, so when restartICE being called repeatedly it caused a lot of new-uuid generated on the server.
Okay, I think I understand.

> 
> Question:
> 
> * should `negotiationneeded` returns the response.headers.get('Location') so it's possible to DELETE it later?
Yes, this is a good idea. Please submit 1 PR for this, if you would like.
Please consider, as your writer your PR:
https://datatracker.ietf.org/doc/html/draft-ietf-wish-whip-02#section-4

> * should we pass a `state` and Location URL into `negotiationneeded` so when the second time it's being triggered it calls PATCH to the Location URL to update SDP instead of calling POST which means create a new one?

Do I understand you are talking about how to implement Trickle ICE, as WHIP does?
see: https://datatracker.ietf.org/doc/html/draft-ietf-wish-whip-02#section-4.1
Please do not submit a PR for this yet, I think we need to discuss this in more detail, so I understand better.

> 
> Thanks.

I appreciate your interest and usage.
Cameron

**Comment by seven1240** [comment]
You are right, the Trickle ICE stuff is a bit complicated, I'm not plan to implement it since it would make the simple protocol complicated. When user need update, they could just stop and start again.

The patch only returns the Location header when it has. See if it makes sense. it's also possible to return the full response.headers but I'm not sure if it's necessary.

The original problem I tried to fix was my server side has problem to setup ICE so the client would try again and again and create a lot of instances on my server side. I resolved that, and now by returning the Location header I can kill it on the page so it's OK for me. I also disabled the restartICE to avoid any side effects, and calls pc.close in my forked example (not in the pr).

https://git.xswitch.cn/xswitch/xcc-examples/src/branch/master/whip

You can change the PR anyway you want.

Thanks.
